<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <AssemblyName>MapGen9000</AssemblyName>
    <RootNamespace>MapGen9000</RootNamespace>
    <ApplicationHighDpiMode>SystemAware</ApplicationHighDpiMode>
    <ApplicationVisualStyles>true</ApplicationVisualStyles>
    <InvariantGlobalization>true</InvariantGlobalization>
    <Version>1.0.0</Version>

    <!-- Publish configuration for Framework-Dependent Single File -->
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>false</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
	<DebugType>none</DebugType>
	<ApplicationIcon>mg.ico</ApplicationIcon>
  </PropertyGroup>

</Project>